esphome:
  name: duc-moc-gateway

esp32:
  board: esp32 # Đổi tên thành mạch chung chung để "lừa" hệ thống qua cửa
  variant: esp32p4 # Khai báo lõi thực sự là P4
  framework:
    type: esp-idf
    # Đã bỏ dòng version để hệ thống tự chọn bản ngon nhất, hết báo vàng

# Cầu nối WiFi (Đã đủ 6 chân tín hiệu chuẩn)
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  active_high: true
  clk_pin: GPIO43
  cmd_pin: GPIO44
  d0_pin: GPIO39
  d1_pin: GPIO40
  d2_pin: GPIO41
  d3_pin: GPIO42

wifi:
  networks:
    - ssid: "......VUPHONG....."
      password: "0913718786@bc.."
    - ssid: "TrungAnh_2.4G"
      password: "0913718786"
  ap:
    ssid: "Duc Moc Gateway Fallback"

api:
ota:
  - platform: esphome

logger:
  level: DEBUG
