name: Build ESPHome Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Đã nâng cấp lên v7 mới nhất của ESPHome
      - uses: esphome/build-action@v7
        id: esphome-build
        with:
          yaml-file: duc-moc-gateway.yaml
          
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: ${{ steps.esphome-build.outputs.name }}
