name: Build ESPHome Firmware
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esphome/build-action@main
        id: esphome-build
        continue-on-error: true # Bỏ qua lỗi Manifest cuối cùng
        with:
          yaml-file: duc-moc-gateway.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          # Lấy chính xác file .bin
          path: .esphome/build/duc-moc-gateway/.pioenvs/duc-moc-gateway/*.bin
