name: Build ESPHome Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: esphome/build-action@main
        id: esphome-build
        continue-on-error: true # Bùa chú: Thằng in nhãn có dỗi cũng mặc kệ, chạy tiếp!
        with:
          yaml-file: duc-moc-gateway.yaml
          
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          # Moi thẳng cục .bin từ trong lò đúc ra gửi về cho anh!
          path: .esphome/build/duc-moc-gateway/.pioenvs/duc-moc-gateway/*.bin
